### ISSUE TITLE
[feature request] song title on menu bar

### ISSUE THREAD

**Issue by drselump14** [arttuperala/kmbmpdc#1]
Hello 

Thank you for this awesome app.
Any plan to show song title next to control button?
I usually get song title using `mpc | head -1`

**Comment by arttuperala** [comment]
> Any plan to show song title next to control button?
You mean in the menu bar itself? I haven't really thought about adding that but I can add it to consideration.

I had an earlier idea of adding the song title/artist/album information inside the kmbmpdc menu, but I haven't really made any solids plans of that. It might just duplicate the information, since if you have kmbmpdc notifications enabled and have them show up in Notification Center, all track information is also stored there. And since kmbmpdc removes prior notifications, it won't clog up your entire Notification Center if you have them appear there as well.

**Comment by drselump14** [comment]
Thanks for the reply...

I see,.. I rarely check notification center,... and checking song title on menu bar is faster than open NC .. 
Currently, I'm using textbar to show the song title on menubar.... 

kmbmpdc is great plugin though, good work 👍👍👍👍👍
