### ISSUE TITLE
Playback support

### ISSUE THREAD

**Issue by toaster** [arttuperala/kmbmpdc#5]
Hi,

MPD supports running a SHOUTcast server.
It would be cool if kmbmpdc could be configured to connect to it when the state is playing or pause. This could be achieved by simply spawning mpg123 with the SHOUTcast URL and killing the process as soon as the state changes to stopped.

**Comment by arttuperala** [comment]
Sounds kind of niche.

**Comment by toaster** [comment]
Dunno … it's the way I listened to my music with my old MBP running Linux.
With the new TouchBar thingy I'm stuck to MacOS and trying to get my old user experience back.

**Comment by toaster** [comment]
mpg123 includes a library … surely this could be used to perform playback without a separate process.

**Comment by arttuperala** [comment]
Rejected since I consider this enhancement too niche for most users and because I don't think it really fits in with the _c_ in _kmbmpdc_.

I imagine this would be better implemented as a separate MPD client. I would also not consider adding Last.fm scrobbling support to kmbmpdc since you can do it better with a separate client designed for it. Also, as libmpdclient and mpg123 are both C libraries, you could probably write a light cross-platform MPD client with C to deal with this.
