### ISSUE TITLE
Playlist editing functionality

### ISSUE THREAD

**Issue by yacoob** [arttuperala/kmbmpdc#8]
This is a feature request. As it stands right now, you can add new songs to the end of current playlist. Within the playlist, you can select a song to 'play next'. It'd be useful if you'd get full playlist editing - moving songs around and removing them. I think mpd protocol allows both of those things.

Thanks!

**Comment by arttuperala** [comment]
Yeah, I've been thinking of having better tools for managing the queue. Adding the removal function is easy since it's just another button next to the _Play next_ button, but the moving part probably needs more thought to be functional.

However, I am currently working on another project (that's somewhat related to this project) and which I want to have up for testing before I do any new work on kmbmpdc. So it may take a while before I get around to it.
